use_frameworks!

target 'BFTask-PromiseKit_Example' do
  pod 'BFTask-PromiseKit', :path => '../'

  target 'BFTask-PromiseKit_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
